### PR TITLE
Docs and Formatting

### PR DESCRIPTION
**Pull request by DGKSK8LIFE**

### CODE REVIEW

**Review by DGKSK8LIFE — COMMENTED** [review]
review plz @matt-mekha @AlexDvorak

**Review by matt-mekha — CHANGES_REQUESTED** [review]
Instead of when statement, make three separate functions for user convenience.

Create a category system so users can organize their log output by subsystem or whatever they choose.

Always write to stdout, even if writing to a file.

**Comment by DGKSK8LIFE** [comment]
> Instead of when statement, make three separate functions for user convenience.
> 
> Create a category system so users can organize their log output by subsystem or whatever they choose.
> 
> Always write to stdout, even if writing to a file.

I'm not going to make 3 separate methods. This is easier and more concise. You're commenting on the wrong PR. I have no idea what you mean  by "category system". I am writing the stdout; `println` is stdout.

**Comment by DGKSK8LIFE** [comment]
just gonna merge with logger PR

**Pull request closed without merging**
